### ISSUE TITLE
Detecting circular linked list in c++

### ISSUE THREAD

**Issue by ojhapiyush** [adarshpand3y/hacktoberfest2022-DSA-excluded#60]
I want to add code to detect circular linked list in c++. Could it be assigned under hacktoberfest.

**Comment by satyamgupta461** [comment]
Hey, I am a 5 star coder at Hackerrank and 3 star at codechef. 
Please assign me this project

**Comment by satyamgupta461** [comment]
@ojhapiyush

**Comment by Ankita-278** [comment]
Can you pls assign me this issue?
